# Generated by Django 3.1.7 on 2021-09-03 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=200, verbose_name='Отчетсво')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Создатель сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип телефонного номера')),
            ],
            options={
                'verbose_name': 'Тип телефонного номера',
                'verbose_name_plural': 'Типы телефонных номеров',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+', help_text='Формат для междугороднего сообщения, начинающийся с "+"', max_length=14, verbose_name='Телефонный номер')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='phobook.employee', verbose_name='Сотрудник')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_phone', to='phobook.phonetype', verbose_name='Тип телефонного номера')),
            ],
            options={
                'verbose_name': 'Телефонный номер',
                'verbose_name_plural': 'Телефонные номера',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название организации')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='Создатель справочника организации')),
                ('list_of_employees', models.ManyToManyField(related_name='list_of_employees', to='phobook.Employee', verbose_name='Список сотрудников')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='phobook.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Модератор организации',
                'verbose_name_plural': 'Модераторы организации',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_numbers',
            field=models.ManyToManyField(blank=True, related_name='phone_of_employee', through='phobook.PhoneNumber', to='phobook.PhoneType', verbose_name='Телефонные номера'),
        ),
        migrations.AddConstraint(
            model_name='moderator',
            constraint=models.UniqueConstraint(fields=('author', 'moderator', 'organization'), name='unique_moderator'),
        ),
    ]
