# Generated by Django 3.1.7 on 2021-09-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobook', '0006_auto_20210904_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['organization', 'id'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='list_of_employees',
            field=models.ManyToManyField(blank=True, related_name='list_of_employees', to='phobook.Employee', verbose_name='Список сотрудников'),
        ),
    ]
