# Generated by Django 3.1.7 on 2021-09-05 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phobook', '0007_auto_20210904_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations_of_employees', to='phobook.organization', verbose_name='Организация'),
        ),
    ]
