# Generated by Django 3.1.7 on 2021-09-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phobook', '0009_auto_20210905_1248'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('second_name', 'first_name', 'patronymic', 'organization'), name='unique_employee'),
        ),
    ]
